apiVersion: launchpad.mirantis.com/v1beta3
kind: DockerEnterprise
metadata:
  name: ucp-kube
spec:
  ucp:
    installFlags:
    - --admin-username=admin
    - --force-minimums
    - --admin-password=passw0rd!
    - --default-node-orchestrator=kubernetes
  hosts:
  ## Public IP address of Manager Node
  ## you can use azure-vm, aws ec2 instance or local virtual-machine
  - address: MasterNode
    role: manager
    ssh:
      user: mahendra
      keyPath: .ssh/id_rsa
  ## Public IP address of worker Node
  - address: node1
    role: worker
    ssh:
      user: mahendra
      keyPath: .ssh/id_rsa
  - address: node2
    role: dtr
    ssh:
      user: mahendra
      keyPath: .ssh/id_rsa
